#!/bin/bash

# Docker Installation Steps for Ubuntu 24.04
# Run these commands manually (requires sudo password)

echo "=== Step 1: Install Docker using official script ==="
echo "Run the following command and enter your password when prompted:"
echo ""
echo "sudo sh get-docker.sh"
echo ""
echo "OR use the manual installation method:"
echo ""
echo "# Update package index"
echo "sudo apt-get update"
echo ""
echo "# Install prerequisites"
echo "sudo apt-get install -y ca-certificates curl"
echo ""
echo "# Add Docker's official GPG key"
echo "sudo install -m 0755 -d /etc/apt/keyrings"
echo "sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc"
echo "sudo chmod a+r /etc/apt/keyrings/docker.asc"
echo ""
echo "# Add Docker repository"
echo 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
echo ""
echo "# Update package index again"
echo "sudo apt-get update"
echo ""
echo "# Install Docker"
echo "sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
echo ""
echo "=== Step 2: Add your user to docker group (to run without sudo) ==="
echo "sudo usermod -aG docker $USER"
echo ""
echo "=== Step 3: Start Docker service ==="
echo "sudo systemctl start docker"
echo "sudo systemctl enable docker"
echo ""
echo "=== Step 4: Test Docker (may need to logout/login or restart) ==="
echo "docker --version"
echo "docker ps"
echo ""
echo "If 'docker ps' fails with permission denied, logout and login again, or run:"
echo "newgrp docker"
